### PR TITLE
Create FAQ.md

### PR DESCRIPTION
**Pull request by brianisbrilliant**
Jim mentioned that he should create this and I thought that might be something that I could do as well. It's an answer to other questions specific to the ICT Game Jam that aren't covered in the specifics that the week-before email will cover.

### CODE REVIEW

**Comment by hitjim** [comment]
So, at first, I was wondering why we wouldn't just cram all these into the main doc?  

Although I could see this list getting long enough, given time, that we'd have wished it were separate.  Something nice to be said for keeping the root README.md short and sweet, with the most common tools and suggestions at the front.

That said, I'd like to see a few changes:
* Use MD syntax rather than HTML for bold
* maybe instead of using a bullet list, give an extra space between each Q/A
* For each Q, keep the whole thing bold, but for A, just bold the A: - as in `**A:** answer text...`
* Provide an answer for that last one.  "Traditionally, we are able to serve lunch for Saturday and Sunday, as well as Dinner on Saturday.  Food, Snacks, and other details may change between events depending on the venue and sponsorship.  If we can guarantee anything we usually mention it in the event description where you claim your ticket."

**Comment by Mottie** [comment]
Would it be better if this was added as a wiki page?

**Comment by hitjim** [comment]
🤔 ... Jim's Strong Personal Opinions inbound!  
* I _always_ forget about the formal WIKI functionality for GH, so I don't want to unintentionally bury content.
* If we eventually get enough content in this thing that it's just broken to not have it in a Wiki, we could move it.  
* If we eventually get enough content in this thing that it's just broken to not have it in a Wiki, it would likely cease to be a useful guide people could give a quick skim.

Great observation though.  As stated, I'd forgotten about GH wikis, and hadn't thought about it.  Feels good to have thought about it 😄

**Comment by brianisbrilliant** [comment]
I love all of it! my only thought for making it it's own page is that people look for the FAQ more specifically than they look for the "guide". If you think it isn't a problem then I'll just merge this into the main doc because I'm a big fan of it all being in one place. Is there a way that we can #tag parts of the document so that we can send people to github.com/ictgamejam-guide/#food and that'll take them directly to a section of the page?

**Comment by hitjim** [comment]
Oh yeah.  I forgot about that.  I see 2 main options:
* Put FAQ at the bottom, but mention it at the top, link or not
* Link directly to the FAQ.md file at the top of the base README.md

**Comment by hitjim** [comment]
I'm going to merge this.  We can tweak it later.  Sorry for the lag @brianisbrilliant

**Pull request merged**
